Update
vuejs/cn.vuejs.org pull request #1119
Opened 2020-09-08 01:56 UTC by Jinjiang

https://github.com/vuejs/vuejs.org/compare/cee0c421...2f4da828

- 忽略了英文版 banner 的一系列变动
- Testing 新文档尚未翻译，会另外发起一个 PR

谢谢

2020-09-08 17:24 UTC, Justineo requested changes

2020-09-08 17:24 UTC, Justineo commented on src/v2/guide/testing.md
> +因为单元测试的建议通常是框架无关的，这里只是当你在评估应用的单元测试工具时需要的一些基本指导。
```suggestion
因为单元测试的建议通常是框架无关的，所以下面只是当你在评估应用的单元测试工具时需要的一些基本指引。
```

2020-09-08 17:24 UTC, Justineo commented on src/v2/guide/testing.md
> +因为主流的单元测试框架都是开源的，所以对于一些旨在长期维护其测试且确保项目本身保持活跃的团队来说，拥有一个活跃的社区时至关重要的。额外的好处是，在任何时候遇到问题时，一个活跃的社区会为你提供更多的支持。
```suggestion
因为主流的单元测试框架都是开源的，所以对于一些旨在长期维护其测试且确保项目本身保持活跃的团队来说，拥有一个活跃的社区是至关重要的。额外的好处是，在任何时候遇到问题时，一个活跃的社区会为你提供更多的支持。
```

2020-09-08 17:24 UTC, Justineo commented on src/v2/guide/testing.md
> +Vue Testing Library 是一组专注于测试组件而不依赖实现细节的工具。在考虑可访问性时，它的方法也使重构变得轻而易举。
```suggestion
Vue Testing Library 是一组专注于测试组件而不依赖实现细节的工具。由于在设计时就充分考虑了可访问性，它采用的方案也使重构变得轻而易举。
```

2020-09-08 17:24 UTC, Justineo commented on src/v2/guide/testing.md
> +Vue Test Utils 是官方的低级组件测试库，它是为用户提供对 Vue 特定 API 的访问而编写的。如果你对测试 Vue 应用不熟悉，我们建议你使用 Vue Testing Library，它是 Vue Test Utils 的抽象。
```suggestion
Vue Test Utils 是官方的偏底层的组件测试库，它是为用户提供对 Vue 特定 API 的访问而编写的。如果你对测试 Vue 应用不熟悉，我们建议你使用 Vue Testing Library，它是 Vue Test Utils 的抽象。
```

2020-09-08 17:24 UTC, Justineo commented on src/v2/guide/testing.md
> +虽然 web 上的端到端 (E2E) 测试因不可信赖 (片面的) 测试和减慢开发过程而得到负面的声誉，但现代 E2E 工具在创建更可靠的、交互的和实用的测试方面取得了长足进步。在选择 E2E 测试框架时，以下章节在你为应用选择测试框架时提供了一些指导。
```suggestion
虽然 web 上的端到端 (E2E，end to end) 测试因不可信赖 (片面的) 测试和减慢开发过程而得到负面的声誉，但现代端到端测试工具在创建更可靠的、交互的和实用的测试方面取得了长足进步。在选择 端到端测试框架时，以下章节在你为应用选择测试框架时提供了一些指导。
```

2020-09-08 17:24 UTC, Justineo commented on src/v2/guide/testing.md
> +端到端 (E2E) 测试和开发的主要问题之一是运行整个套件需要很长时间。通常，这只在持续集成和部署 (CI/CD) 管道中完成。现代的 E2E 测试框架通过添加类似并行化的特性来帮助解决这个问题，这使得 CI/CD 管道的运行速度通常比以前快。此外，在本地开发时，有选择地为正在处理的页面运行单个测试的能力，同时还提供测试的热重新加载，这有助于提高开发者的工作流程和工作效率。
```suggestion
端到端 (E2E) 测试和开发的主要问题之一是运行整个套件需要很长时间。通常，这只在持续集成和部署 (CI/CD) 管道中完成。现代的端到端测试框架通过添加类似并行化的特性来帮助解决这个问题，这使得 CI/CD 管道的运行速度通常比以前快。此外，在本地开发时，有选择地为正在处理的页面运行单个测试的能力，同时还提供测试的热重载，将有助于提高开发者的工作流程和工作效率。
```

2020-09-09 15:05 UTC, Jinjiang commented on src/v2/guide/testing.md
> +虽然 web 上的端到端 (E2E) 测试因不可信赖 (片面的) 测试和减慢开发过程而得到负面的声誉，但现代 E2E 工具在创建更可靠的、交互的和实用的测试方面取得了长足进步。在选择 E2E 测试框架时，以下章节在你为应用选择测试框架时提供了一些指导。
这里要展开届时 end to end 吗?文章再？之前出现的时候都没有这样展开解释

2020-09-09 15:21 UTC, Justineo commented on src/v2/guide/testing.md
> +虽然 web 上的端到端 (E2E) 测试因不可信赖 (片面的) 测试和减慢开发过程而得到负面的声誉，但现代 E2E 工具在创建更可靠的、交互的和实用的测试方面取得了长足进步。在选择 E2E 测试框架时，以下章节在你为应用选择测试框架时提供了一些指导。
感觉这个缩写很多人不熟悉？你觉得需要展开下么

2020-09-09 16:28 UTC, Jinjiang commented on src/v2/guide/testing.md
> +虽然 web 上的端到端 (E2E) 测试因不可信赖 (片面的) 测试和减慢开发过程而得到负面的声誉，但现代 E2E 工具在创建更可靠的、交互的和实用的测试方面取得了长足进步。在选择 E2E 测试框架时，以下章节在你为应用选择测试框架时提供了一些指导。
可以在第一次出现的地方加上，第 15 行那里

2020-09-11 00:03 UTC, Justineo approved these changes

2020-09-11 00:03 UTC, merged